export const RECIPE_CATEGORY = [
  "Appetizer / Starter",
  "Main Course",
  "Side Dish",
  "Dessert",
  "Soup",
  "Salad",
  "Bread",
  "Beverage / Drink",
  "Sauce",
  "Spread / Dip",
  "Marinade",
  "Dressing",
];

export const RECIPE_CUISINE = [
  "Italian",
  "French",
  "Spanish",
  "Mexican",
  "American",
  "Mediterranean",
  "Middle Eastern",
  "Indian",
  "Chinese",
  "Japanese",
  "Thai",
  "Korean",
  "Vietnamese",
  "Nordic / Scandinavian",
  "African",
  "Latin American",
];
