import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { NavBar } from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-svh`}
      >
        <header className="sticky top-0 z-10 py-2 bg-gray-100 dark:bg-gray-900">
          <NavBar />
        </header>
        <main className="flex-1 min-h-0 flex justify-center">{children}</main>
        <footer className="px-4 py-2">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
